#!/usr/bin/python

from __future__ import print_function
from sys import stdin, exit
import random
from random import randrange
from collections import namedtuple
import re

random.seed()

Primes = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,167,173,179,181,191,193,197,199,211,223,227,229,233,239,241,251,257,263,269,271,277,281,283,293,307,311,313,317,331,337,347,349,353,359,367,373,379,383,389,397,401,409,419,421,431,433,439,443,449,457,461,463,467,479,487,491,499,503,509,521,523,541,547,557,563,569,571,577,587,593,599,601,607,613,617,619,631,641,643,647,653,659,661,673,677,683,691,701,709,719,727,733,739,743,751,757,761,769,773,787,797,809,811,821,823,827,829,839,853,857,859,863,877,881,883,887,907,911,919,929,937,941,947,953,967,971,977,983,991,997]

NiceFriendlyPrimes = [2,3,5]
NiceFriendlyNumbers = [2,3,4,5,6,8,9,16]

def common(l1, l2):
	l2 = l2[:]
	common = [ e for e in l1 if e in l2 and (l2.pop(l2.index(e)) or True)]
	return common

def diff(l1, l2):  # that's subtractive, not symmetric!
	o = l1[:]
	for i in l2:
		if i in o:
			o.pop(o.index(i))
	return o

# BEGIN SELF TEST
assert(diff([],[]) == [])
assert(diff([],[1]) == [])
assert(diff([1],[]) == [1])
assert(diff([1,1,2,3,3,3,4],[]) == [1,1,2,3,3,3,4])
assert(diff([1,1,2,3,3,3,4],[1]) == [1,2,3,3,3,4])
assert(diff([1,1,2,3,3,3,4],[4]) == [1,1,2,3,3,3])
assert(diff([1,1,2,3,3,3,4],[3]) == [1,1,2,3,3,4])
assert(diff([1,1,2,3,3,3,4],[1,1,3,4,5]) == [2,3,3])
assert(common([],[]) == [])
assert(common([],[1]) == [])
assert(common([1],[]) == [])
assert(common([1,1,2,3,3,3,4],[]) == [])
assert(common([1,1,2,3,3,3,4],[1]) == [1])
assert(common([1,1,6,2,3,3,3,4],[4,6,3]) == [6,3,4])
assert(common([1,1,2,3,3,3,4],[1,1,3,4,5,7]) == [1,1,3,4])

class Fraction(namedtuple('Fraction', ['numerator', 'denominator'])):
	def __repr__(self):
		return "{}/{}".format(self.numerator, self.denominator)
	
	def nice_repr(self):
		if self.numerator / self.denominator == 0:
			return self.__repr__()
		if self.numerator % self.denominator == 0:
			return str(self.numerator)
		return "{} {}/{}".format(self.numerator/self.denominator, self.numerator%self.denominator, self.denominator)
	
	def simplified(self):
		numf = factorize(self.numerator)
		denf = factorize(self.denominator)
		comm = common(numf, denf)
		#print()
		#print("{} {}".format(numf, denf))
		#print("{} {} {}".format(comm, diff(numf, comm), diff(denf, comm)))
		return Fraction(reduce(lambda x,y: x*y, diff(numf, comm), 1), reduce(lambda x,y: x*y, diff(denf, comm), 1))

def try_parse_frac(strang):
	try:
		m = re.match("(\\d+) (\\d+)/(\\d+)$", strang)
		if m:
			i, n, d = (int(n) for n in m.groups())
		m = re.match("(\\d+)/(\\d+)$", strang)
		if m:
			i, (n, d) = (0, (int(n) for n in m.groups()))
		m = re.match("(\\d+)$", strang)
		if m:
			i, (n, d) = (int(m.group(1)), (0,1))
		return Fraction((i*d)+n, d)
	except UnboundLocalError:
		return None

# BEGIN SELF TEST
assert(try_parse_frac("14 4/5") == Fraction(74,5))
assert(try_parse_frac("144/5") == Fraction(144,5))
assert(try_parse_frac("14") == Fraction(14,1))
assert(try_parse_frac("14 4 45") == None)

class Problem(namedtuple('Problem', ['left', 'operator', 'right'])):
	def __repr__(self):
		return str(self.left) + ' ' + self.operator + ' ' + str(self.right)
	
	def solution(self):
		if self.operator == '+':
			fn = lambda (a,b),(x,y): Fraction((a*y + b*x), (b*y))
		elif self.operator == 'x':
			fn = lambda (a,b),(x,y): Fraction((a*x), (b*y))
		else:
			raise ValueError("What the hell is {}".format(self.operator))
		return fn(self.left, self.right).simplified()


def is_friendly(n):  # i.e. is this a denominator it's currently reasonable to ask for as a decimal?
	# factorized = factorize(n)
	# return len(factorized) < 4 and all(p in NiceFriendlyPrimes for p in factorized)
	return n in NiceFriendlyNumbers

def factorize(n):
	if n < 1:
		raise AssertionError("Can't factorize an un-natural number")
	if n == 1:
		return []
	for p in Primes:
		if n % p == 0:
			ans = factorize(n / p)
			ans.append(p)
			return ans
	else:
		raise AssertionError("Oh no. I've been fed a large prime that isn't in my shoddily defined array")

def __choose_fraction():
	while True:
		d = randrange(2, 1000)
		if is_friendly(d):
			if randrange(2) == 0:  # arbitrary chance of being "top-heavy"
				yield Fraction(randrange(1, d), d)
			else:
				yield Fraction(randrange(d + 1, d*10), d)
_choose_fraction = __choose_fraction()  # TODO this is extremely annoying, try to find a way to wrap the generator nicely
def choose_fraction():
	return _choose_fraction.next()

def choose_problem():
	p = {}
	while True:
		problem = Problem(choose_fraction(), random.choice(['+','x']), choose_fraction())
		print(problem, end='  ')
		print(problem.left.simplified(), end=' ')
		print(problem.right.simplified(), end='  ')
		print(problem.solution().nice_repr(), end=' ')
		print('good')
		return problem

for i in xrange(30):
	choose_problem()

# BEGIN SELF TEST
assert(Fraction(1,2).simplified() == Fraction(1,2))
assert(Fraction(23,3).simplified() == Fraction(23,3))
assert(Fraction(87,9).simplified() == Fraction(29,3))
exit(40)

while True:
	problem = {}
	bored = False
	while not bored:
		print(problem)
		print('answer? : ', end='')
		input = stdin.readline()
		if input.strip() == 'b':  # it's a boring problem
				boring = True
				break
		print('potato')
